---
apiVersion: v1
kind: Service
metadata:
  name: svc-$APP$-$TEMPLATE$
  namespace: ns-rsync
  labels:
    app: $APP$
    mod: '$TEMPLATE$'
    project: rsync
spec:
  ports:
    - port: 22
      protocol: TCP
      nodePort: 303$TEMPLATE$
  selector:
    app: $APP$
    mod: '$TEMPLATE$'
    project: rsync
  type: NodePort
...


