---
apiVersion: v1
kind: Service
metadata:
  name: svc-$BOTNET_NAME$-$BOT_NUMBER$
  namespace: ns-botnet
  labels:
    app: $BOTNET_NAME$
    bot_number: '$BOT_NUMBER$'
    image: rhel_ansible_basic_node-_-latest
    project: botnet_generator
    role: bot
spec:
  ports:
  - port: 22
    protocol: TCP
    nodePort: 303$BOT_NUMBER$
  selector:
    app: $BOTNET_NAME$
    bot_number: '$BOT_NUMBER$'
    image: rhel_ansible_basic_node-_-latest
    project: botnet_generator
    role: bot
  type: NodePort
...


